name: pokedex_flutter
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_staggered_animations:
  simple_animations:
  cupertino_icons:
  get_it:
  intl:
  http:
  sliding_sheet:
  mobx:
  flutter_mobx:
  shared_preferences: ^2.2.3
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  mobx_codegen:
  build_runner:

flutter:
  uses-material-design: true

  assets:
    - assets/images/background/
    - assets/images/pokedex/thumbnails/
    - assets/images/pokedex/hires/
    - assets/images/pokedex/sprites/
    - assets/images/items/sprites/
    - assets/items.json
    - assets/moves.json
    - assets/types.json
    - assets/pokedex.json

  fonts:
    - family: Google
      fonts:
        - asset: assets/fonts/ProductSans-Regular.ttf
        - asset: assets/fonts/ProductSans-Bold.ttf
          weight: 700
